#! /bin/sh


#++++++++++++++++++# 
#      ALIAS       #
#++++++++++++++++++# 

if [[ "$OSTYPE" == "darwin"* ]]; then
# == Mac ================ #

# cd alias
alias cd-dev="cd ~/Documents/Dev"
alias cd-thesis="cd ~/Documents/NTHU/toMaster/thesis"

# Let brew know I have pyenv
alias brew="env PATH='${PATH//$(pyenv root)\/shims:/}' brew"
alias backup-brew="brew bundle dump --file=${KAKU_ROOT}/homebrew/Brewfile --force --describe"

alias pyenv='env LDFLAGS="-L/usr/local/opt/zlib/lib" CPPFLAGS="-I/usr/local/opt/zlib/include" pyenv'

alias nproc='sysctl -n hw.logicalcpu'
alias load_drivers='launchctl load /Library/LaunchAgents/*'
alias unload_drivers='launchctl unload /Library/LaunchAgents/*'


elif [[ "$OSTYPE" == "linux-gnu"* ]]; then

# == Linux ================ #
  :
fi

# Quick Back
alias ...='../..'
alias ....='../../..'
alias .....='../../../..'
alias ......='../../../../..'
alias .......='../../../../../..'

# fzf
# fzf must source before kakufile
if command -v fzf &> /dev/null ;then
  alias fp="cat /etc/services | fzf"
  alias flsof4="lsof -Pn -i4 | awk '{printf \"%10s %6s %5s %4s %-20s\n\", \$1, \$2, \$3, \$8, \$9}' | fzf --border --cycle --ansi --header-lines=1"
  alias gcob='git checkout $(git branch | fzf --cycle --border --ansi)'
  alias gadd="git status --short | fzf --multi --color=dark --cycle --border --ansi --preview-window=up:70% --preview=\"git diff --color {+2}\" | awk '{print \$2}'  | xargs git add"
  alias gco="git diff --name-only | fzf --multi --color=dark --cycle --border --ansi --preview-window=up:70% --preview=\"git diff --color {+1}\" | xargs git checkout"
  alias gustg="git diff --name-only --cached | fzf --multi --color=dark --cycle --border --ansi --preview-window=up:70% --preview="git diff --color --staged {+1}" | xargs git reset HEAD"
  alias gbrd="git branch --color=always | fzf --multi --color=dark --cycle --border --ansi | sed 's/*//' | awk '{print \$1}' | xargs git branch -d"
fi

# lsd
if command -v lsd &> /dev/null ;then
  alias ls='lsd'
  alias l='ls -l'
  alias la='ls -a'
  alias lla='ls -la'
  alias lt='ls --tree'
fi

# WAN ip
alias catpubip='echo "My WAN/Public IP address: $(curl ifconfig.me -s)"'
alias ipinfo='curl -sH "Accept: application/json" ipinfo.io | jq'

alias lg='lazygit'

# restart zsh
alias restart="clear && exec $SHELL"

# test zsh start time
alias start-count="time zsh -i -c echo"

alias vtop="vtop --theme brew"

alias lsports='lsof -ni | grep LISTEN'
