tap "homebrew/bundle"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/command-not-found"
tap "homebrew/services"
tap "yt-dlp/taps"
# General-purpose data compression with high compression ratio
brew "xz"
# Library for command-line editing
brew "readline"
# Download with resuming and segmented downloading
brew "aria2"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Cross-platform make
brew "cmake"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# Command-line fuzzy finder written in Go
brew "fzf"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Syntax-highlighting pager for git and diff output
brew "git-delta"
# Git extension for versioning large files
brew "git-lfs"
# GNU Pretty Good Privacy (PGP) package
brew "gnupg"
# Post-modern modal text editor
brew "helix"
# Improved top (interactive process viewer)
brew "htop"
# Configurable static site generator
brew "hugo"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Fast, Dynamic Programming Language
brew "julia"
# Clone of ls with colorful output, file type icons, and more
brew "lsd"
# Mac App Store command-line interface
brew "mas"
# Interactive cheatsheet tool for the command-line
brew "navi"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Small build system for use with gyp or CMake
brew "ninja"
# Platform built on V8 to build network applications
brew "node"
# Interpreted, interactive, object-oriented programming language
brew "python@3.11"
# Python dependency management tool
brew "pipenv"
# Python version management
brew "pyenv"
# Pyenv plugin to manage virtualenv
brew "pyenv-virtualenv"
# Interpreted, interactive, object-oriented programming language
brew "python@3.10"
# Interpreted, interactive, object-oriented programming language
brew "python@3.9"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Utility that provides fast incremental file transfer
brew "rsync"
# Rust toolchain installer
brew "rustup-init"
# Intuitive find & replace CLI
brew "sd"
# Terminal multiplexer
brew "tmux"
# Vi 'workalike' with many additional features
brew "vim"
# Internet file retriever
brew "wget"
# JavaScript package manager
brew "yarn"
# Pluggable terminal workspace, with terminal multiplexer as the base feature
brew "zellij"
# UNIX shell (command interpreter)
brew "zsh"
# A youtube-dl fork with additional features and fixes
brew "yt-dlp/taps/yt-dlp"
# GPU-accelerated terminal emulator
cask "alacritty"
# Application uninstaller
cask "appcleaner"
# Disk space visualizer
cask "daisydisk"
# Utilities designed to make common development tasks easier
cask "devtoys"
# Voice and text chat software
cask "discord"
# Online diagram software
cask "drawio"
# Sans-serif, slab-serif, monospace and quasi‑proportional typeface family
cask "font-iosevka-aile"
# Sans-serif, slab-serif, monospace and quasi‑proportional typeface family
cask "font-iosevka-etoile"
# Developer targeted fonts with a high number of glyphs
cask "font-mononoki-nerd-font"
cask "font-noto-sans-cjk"
cask "font-powerline-symbols"
# Audio player
cask "foobar2000"
# Utility to hide menu bar items
cask "hiddenbar"
# Free and open-source media player
cask "iina"
# File archiver
cask "keka"
# End-to-end encryption software
cask "keybase"
# Open-source keystroke visualizer
cask "keycastr"
# Sandbox construction video game
cask "minecraft"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# Bridges Proton Mail to email clients supporting IMAP and SMTP protocols
cask "protonmail-bridge"
# PDF reader and note-taking application
cask "skim"
# Open-source code editor
cask "visual-studio-code"
# GPU-accelerated cross-platform terminal emulator and multiplexer
cask "wezterm"
# Lossless audio decoder
cask "xld"
mas "Affinity Photo", id: 824183456
mas "GarageBand", id: 682658836
mas "Gifski", id: 1351639930
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Logic Pro", id: 634148309
mas "MainStage", id: 634159523
mas "Notability", id: 360593530
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Telegram", id: 747648890
mas "Twitter", id: 1482454543
mas "uBlacklist for Safari", id: 1547912640
vscode "alexanderbast.vscode-snazzy"
vscode "christian-kohler.path-intellisense"
vscode "eamodio.gitlens"
vscode "julialang.language-julia"
vscode "PKief.material-icon-theme"
vscode "vscodevim.vim"
