#! /bin/sh

if [ "$(uname)" = "Darwin" ]; then
  alias backup-brew='brew bundle dump --file=${KAKU_ROOT}/homebrew/Brewfile --force --describe'
  alias nproc='sysctl -n hw.logicalcpu'
fi

# Quick Back
alias ...='../..'
alias ....='../../..'
alias .....='../../../..'
alias ......='../../../../..'
alias .......='../../../../../..'

# fzf
if command -v fzf > /dev/null ;then
  alias fp='cat /etc/services | fzf'
  alias exehis='eval $(history -n -1 1 | fzf --multi --color=dark --cycle --border --ansi)'
fi

# lsd
if command -v lsd > /dev/null ;then
  alias ls='lsd'
  alias l='ls -l'
  alias la='ls -a'
  alias lla='ls -la'
  alias lt='ls --tree'
fi

# WAN ip
if command -v curl > /dev/null ;then
  alias catpubip='echo "My WAN/Public IP address: $(curl ifconfig.me -s)"'
  alias ipinfo='curl -sH "Accept: application/json" ipinfo.io | jq'
  alias wttr='curl wttr.in -s | sed "s/(Province of China)//g"'
fi

# restart zsh
alias restart='clear && exec $SHELL'

# test zsh start time
alias startuptime="time zsh -i -c echo"

# Alia to new session
if command -v tmux > /dev/null ;then
  alias tnew="tmux new-session -A -s"
fi
