#! /bin/sh

if [[ "$OSTYPE" == "darwin"* ]]; then
  dir() {
  # Easy open dir
    open "$(pwd)"
  }
fi

# Beautifully print your path
 echopath() {
  if [ $+PATH ]; then
    echo "\033[1m\033[1;34m  < $#path element(s) >\033[1;32m"
    printf '├─ %q\n' "$path[@]"
    echo "\033[0m"
  else
    echo "\033[0;31mPATH unset\033[0m"
  fi
}

 gi() {
  curl -sLw n https://www.gitignore.io/api/$@ ;
}

 cht() {
  if command -v bat &> /dev/null; then
    cht.sh $1 | bat --style plain
  else
    cht.sh $1 | less
  fi
}

 mergepdfs() {
  if command -v gs &> /dev/null; then
    gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite -sOutputFile=$1 "${@:2}"
  else
    echo "Ghost script not installed."
  fi
}

# fzf git diff
fgdiff() {
  preview="git diff $@ --color=always -- {-1}"
  git diff $@ --name-only | fzf -m --ansi --preview $preview
}

# See https://transfer.sh
transfer(){ if [ $# -eq 0 ];then echo "No arguments specified.\nUsage:\n transfer <file|directory>\n ... | transfer <file_name>">&2;return 1;fi;if tty -s;then file="$1";file_name=$(basename "$file");if [ ! -e "$file" ];then echo "$file: No such file or directory">&2;return 1;fi;if [ -d "$file" ];then file_name="$file_name.zip" ,;(cd "$file"&&zip -r -q - .)|curl --progress-bar --upload-file "-" "https://transfer.sh/$file_name"|tee /dev/null,;else cat "$file"|curl --progress-bar --upload-file "-" "https://transfer.sh/$file_name"|tee /dev/null;fi;else file_name=$1;curl --progress-bar --upload-file "-" "https://transfer.sh/$file_name"|tee /dev/null;fi;}
